stages:
  - lint
  - test

variables:
  IMAGE_URL: artifactory.pegadaian.co.id:5443/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  PACKAGE_PATH: /go/src/gade/srv-gade-point

# A hack to make Golang-in-Gitlab happy
.anchors:
  - &inject-gopath
      export GO111MODULE=on
      && export PATH="$PATH:/go/bin"
      && export GOPRIVATE="https://artifactory.pegadaian.co.id/repository/go-group-01/"
      && export GOPROXY="https://artifactory.pegadaian.co.id/repository/go-group-01/"
      && export GONOSUMDB="github.com/*,golang.org/*,gopkg.in/*,gitlab.com/*,cloud.google.com/*,go.*,google.golang.org/*,gotest.*,honnef.co/*,mellium.im/*"
      && cp ${ARTIFACTORY_SSL_CERT} /usr/local/share/ca-certificates/ssl_certificate.crt
      && chmod 644 /usr/local/share/ca-certificates/ssl_certificate.crt && update-ca-certificates

lint:
  image:
    name: artifactory.pegadaian.co.id:8084/golangci/golangci-lint:v1.42.1
    entrypoint: [""]
  stage: lint
  before_script:
    - *inject-gopath
  script:
    - go mod download
    - golangci-lint run
  only:
    - master
    - merge_requests

test:
  stage: test
  image: artifactory.pegadaian.co.id:8084/golang:1.17.8
  before_script:
    - *inject-gopath
  script:
    - go mod download
    - go test -coverprofile=coverage.out ./...
  only:
    - master
    - merge_requests